name: Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            artifact: whats4linux-linux-amd64
            webkit: true

          - os: windows-latest
            platform: windows/amd64
            artifact: whats4linux-windows-amd64
            webkit: false

          - os: macos-latest
            platform: darwin/amd64
            artifact: whats4linux-macos-amd64
            webkit: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Linux-only system deps
      - name: Install Linux dependencies
        if: matrix.webkit
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Wails app
        run: |
          wails build \
            -platform ${{ matrix.platform }} \
            ${{ matrix.webkit && '-tags webkit2_41' || '' }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/bin/*
